CREATE TABLE portfolios (
            portfolioname varchar(150),
            layerid BIGINT NOT NULL,
            id BIGINT NOT NULL,
            countrycode varchar(50),
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            income_group INTEGER, 
            tsi_group varchar(50),
            sum_insured DOUBLE PRECISION,
            has_losses BOOLEAN,
            losses DOUBLE PRECISION,
            building_type varchar(50), 
            sample_rating varchar(50),
            geohash_1 varchar(50),
            geohash_2 varchar(50),
            geohash_3 varchar(50),
            geohash_4 varchar(50),
            geohash_5 varchar(50),
            geohash_6 varchar(50),
            geohash_7 varchar(50),
            geohash_8 varchar(50),
            earthquake  SMALLINT,
            hail  SMALLINT,
            heat_wave  SMALLINT,
            tornado  SMALLINT
    );