version: "3"

services:
  db:
    # image: omnisci/core-os-cuda
    image: omnisci/omnisci-ee-cuda
    runtime: nvidia
    restart: always
    ipc: host
    ports:
      - 6273-6280:6273-6280
    volumes:
      - ./omnisci-storage_10x:/omnisci-storage
